project:
  name: quickstart-atlassian-crowd
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-1
  s3_bucket: ''
tests:
  crowd:
    parameters:
      AccessCIDR: 10.0.0.0/16
      AvailabilityZones: $[taskcat_genaz_2]
      CustomDnsName: qscrowdci.awsqs.com
      DBMasterUserPassword: f925dO1ry_
      DBMultiAZ: 'false'
      DBPassword: f925dO1ry_
      DBStorage: '100'
      DBStorageType: Provisioned IOPS
      KeyPairName: replaced-by-taskcat-override-file
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-atlassian-crowd/
    regions:
      - us-east-1
    s3_bucket: ''
    template: templates/quickstart-crowd-dc-with-vpc.template.yaml